#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Ryuichi Ueda
# SPDX-License-Identifier: DSD-3-Clause
import sys

ans = 0
for line in sys.stdin:
	try:
		ans += int(line)
	except:
		ans += float(line)

print(ans)


